# Generated by Django 3.2.9 on 2022-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sym', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=500)),
                ('date_l', models.DateField()),
                ('paid_u', models.IntegerField()),
                ('isin_n', models.CharField(max_length=500)),
                ('face_v', models.IntegerField()),
                ('open_v', models.FloatField()),
                ('close_v', models.FloatField()),
                ('high_v', models.FloatField()),
                ('last_v', models.FloatField()),
                ('low_v', models.FloatField()),
                ('prev_v', models.FloatField()),
                ('total_w', models.FloatField()),
                ('time_s', models.DateField()),
                ('total_rd', models.FloatField()),
                ('total_t', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
