# Generated by Django 3.2.9 on 2022-03-31 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20220331_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='close_v',
            new_name='Close_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='face_v',
            new_name='Face_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='high_v',
            new_name='High_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='isin_n',
            new_name='Isin_n',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='last_v',
            new_name='Last_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='low_v',
            new_name='Low_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='open_v',
            new_name='Open_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='paid_u',
            new_name='Paid_u',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='prev_v',
            new_name='Prev_v',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='stock_sym',
            new_name='Stock_sym',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='total_rd',
            new_name='Total_rd',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='total_t',
            new_name='Total_t',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='total_w',
            new_name='Total_w',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='date_l',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='time_s',
        ),
        migrations.AddField(
            model_name='stocks',
            name='Stock_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='DELIV_PER',
            field=models.FloatField(),
        ),
    ]
